version: '3'
services:
  winserver-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-winserver-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_winserver_api:/usr/lib/python3.6/site-packages/vlab_winserver_api
    command: ["python3", "app.py"]

  winserver-worker:
    image:
      willnx/vlab-winserver-worker
    volumes:
      - ./vlab_winserver_api:/usr/lib/python3.6/site-packages/vlab_winserver_api
      - /mnt/raid/images/winserver:/images:ro
    environment:
      - INF_VCENTER_SERVER=changeME
      - INF_VCENTER_USER=changeME
      - INF_VCENTER_PASSWORD=changeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  winserver-broker:
    image:
      rabbitmq:3.7-alpine
